apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-ui
  template:
    metadata:
      labels:
        app: ticket-ui
    spec:
      containers:
      - name: ticket-ui
        image: m311/ticket-ui:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-ui
spec:
  type: NodePort
  selector:
    app: ticket-ui
  ports:
  - port: 8080
    nodePort: 30080
